# Generated by Django 4.1.7 on 2023-04-04 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
